scaffold(workflows): attempt to get more details on eslint/reviewdog

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,15 +26,31 @@ jobs:
     - name: Install dependencies
       run: npm ci
 
-    - name: ESLint and report to PR
-      id: reviewdog
-      uses: reviewdog/action-eslint@v1
+    - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        reporter: github-check
-        eslint_flags: 'src/**/*.ts'
-        filter_mode: file
-        fail_level: any
+        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
+
+    - name: lint
+      id: lint
+      run: |
+        npx eslint 'src/**/*.ts' -f rdjson -o eslint-report.json
+        echo "lint_exit_code=$?" >> "$GITHUB_OUTPUT"
+
+    - name: Publish lint results
+      id: reviewdog
+      run: |
+        reviewdog -f=rdjson -reporter=github-check -name="ESLint" < eslint-report.json
+        echo "reviewdog_exit_code=$?" >> "$GITHUB_OUTPUT"
+
+#    - name: ESLint and report to PR
+#      id: reviewdog
+#      uses: reviewdog/action-eslint@v1.33.2
+#      with:
+#        github_token: ${{ secrets.GITHUB_TOKEN }}
+#        reporter: github-check
+#        eslint_flags: 'src/**/*.ts'
+#        filter_mode: file
+#        fail_level: any
 
     - name: Capture lint exit code
       id: lint-capture
